version: '3'

services:
  storage:
    image: flix-storage
    build:
      context: ./storage
      dockerfile: Dockerfile

    container_name: flix-storage

    ports:
      - "4001:80"

    environment:
      - PORT=80
      - DEBUG=storage*
      - STORAGE_BUCKET=videos
      - STORAGE_ENDPOINT=object-storage
      - STORAGE_KEY=${STORAGE_KEY}
      - STORAGE_SECRET=${STORAGE_SECRET}

    restart: "no"

  video-streaming:
    image: flix-streaming
    build:
      context: ./video-streaming
      dockerfile: docker/Dockerfile

    container_name: flix-streaming

    ports:
      - "4000:80"

    environment:
      - PORT=80
      - DEBUG=video-streaming*
      - STORAGE_HOST=storage
      - STORAGE_PORT=80
      - DB_HOST=mongodb://${DB_USER}:${DB_PASSWORD}@db:27017
      - DB_NAME=video-streaming
      - RABBIT=amqp://guest:guest@rabbit:5672

    depends_on:
      - db
      - rabbit

    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z

    restart: "always"

  object-storage:
    image: quay.io/minio/minio
    command:
      - server
      - /data
      - --console-address
      - ":9090"

    environment:
      - MINIO_ROOT_USER=${STORAGE_KEY}
      - MINIO_ROOT_PASSWORD=${STORAGE_SECRET}

    ports:
      - "9000:9000"
      - "9090:9090"

    volumes:
      - $PWD/data/object:/data

  db:
    image: mongo:5.0.9
    container_name: db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: video-streaming

    ports:
      - "4002:27017"

    volumes:
      - $PWD/data/mongo:/data/db

    restart: "always"

  history:
    image: history

    build:
      context: ./history
      dockerfile: docker/Dockerfile

    container_name: history

    environment:
      PORT: 80
      DEBUG: history*
      NODE_ENV: development
      DB_HOST: mongodb://${DB_USER}:${DB_PASSWORD}@db:27017
      DB_NAME: history
      RABBIT: amqp://guest:guest@rabbit:5672

    depends_on:
      - db
      - rabbit

    ports:
      - "4003:80"

    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z

    restart: "no"

  rabbit:
    image: rabbitmq:3.9.21-management
    container_name: rabbit

    ports:
      - "5672:5672"
      - "15672:15672"

    expose:
      - "5672"
      - "15672"

    restart: "always"

    volumes:
      - $PWD/data/rabbitmq:/var/lib/rabbitmq/mnesia