version: '3'

services:
  storage:
    image: flix-storage
    build:
      context: ./storage
      dockerfile: Dockerfile

    container_name: flix-storage

    ports:
      - "4001:80"

    environment:
      - PORT=80

    restart: "no"

  video-streaming:
    image: flix-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile

    container_name: flix-streaming

    ports:
      - "4000:80"

    environment:
      - PORT=80

    restart: "no"